module.exports = {
    moduleFileExtensions: ['js', 'json', 'ts'],
    rootDir: 'src',
    testRegex: '.*\\.spec\\.ts$',
    transform: {
      '^.+\\.(t|j)s$': 'ts-jest',
    },
    collectCoverageFrom: ['**/*.(t|j)s'],
    coverageDirectory: '../coverage',
    testEnvironment: 'node',
    setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
    moduleNameMapper: {
      '^src/(.*)$': '<rootDir>/$1',
    },
    coveragePathIgnorePatterns: [
      '/node_modules/',
      '/dist/',
      '/src/dto',
      '/src/migration/',
      '/src/test/',
      '/src/utils/(?!utility/)[^/]+/',
      '/src/main.ts',
      '/src/modules/.*/dto/',
      '/src/modules/.*/entities/',
      '/src/modules/.*/guards/',
      '/src/modules/users/queries/',
      '/src/modules/common/file-upload/decorator/',
      '.*\\.repository\\.ts$',
      '.*\\.module\\.ts$',
      '.*\\.interceptor\\.ts$',
    ],
    coverageThreshold: {
      global: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
  };