export enum CommunicationChannel {
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  SMS = 'SMS',
  PUSH_NOTIFICATION = 'PUSH_NOTIFICATION',
}

export enum CommunicationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  BOUNCED = 'BOUNCED',
  READ = 'READ',
}

export enum CommunicationCategory {
  // Approval notifications
  ATTENDANCE_APPROVAL = 'ATTENDANCE_APPROVAL',
  ATTENDANCE_REGULARIZATION = 'ATTENDANCE_REGULARIZATION',
  EXPENSE_APPROVAL = 'EXPENSE_APPROVAL',
  FUEL_EXPENSE_APPROVAL = 'FUEL_EXPENSE_APPROVAL',
  LEAVE_APPROVAL = 'LEAVE_APPROVAL',

  // Reminders
  LEAVE_APPROVAL_REMINDER = 'LEAVE_APPROVAL_REMINDER',
  ATTENDANCE_APPROVAL_REMINDER = 'ATTENDANCE_APPROVAL_REMINDER',
  EXPENSE_APPROVAL_REMINDER = 'EXPENSE_APPROVAL_REMINDER',

  // Document expiry
  VEHICLE_DOCUMENT_EXPIRY = 'VEHICLE_DOCUMENT_EXPIRY',
  ASSET_WARRANTY_EXPIRY = 'ASSET_WARRANTY_EXPIRY',
  ASSET_CALIBRATION_EXPIRY = 'ASSET_CALIBRATION_EXPIRY',
  CARD_EXPIRY = 'CARD_EXPIRY',

  // Service
  VEHICLE_SERVICE_DUE = 'VEHICLE_SERVICE_DUE',

  // HR
  BIRTHDAY_WISH = 'BIRTHDAY_WISH',
  WORK_ANNIVERSARY = 'WORK_ANNIVERSARY',
  PAYSLIP = 'PAYSLIP',
  FNF_DOCUMENTS = 'FNF_DOCUMENTS',
  WELCOME_EMPLOYEE = 'WELCOME_EMPLOYEE',

  // Auth
  FORGET_PASSWORD = 'FORGET_PASSWORD',
  OTP = 'OTP',

  // Config
  FY_LEAVE_CONFIG_REMINDER = 'FY_LEAVE_CONFIG_REMINDER',

  // General
  OTHER = 'OTHER',
}

export enum CommunicationPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export const COMMUNICATION_LOG_ERRORS = {
  NOT_FOUND: 'Communication log not found',
  FAILED_TO_LOG: 'Failed to log communication',
};

export const COMMUNICATION_LOG_SUCCESS = {
  LOGGED: 'Communication logged successfully',
};

export const EMAIL_RETRY_CONFIG = {
  MAX_RETRIES: 3,
  BASE_DELAY_MINUTES: 1,
  DELAY_MULTIPLIER: 5, // Delays: 1min, 5min, 25min (5^0, 5^1, 5^2)
};
